# Generated by Django 3.1.6 on 2021-02-15 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(db_column='First Name', max_length=50)),
                ('last_name', models.CharField(db_column='Last Name', max_length=50)),
                ('profile_picture', models.CharField(db_column='Profile picture', default='default_teacher.png', max_length=50)),
                ('email_address', models.CharField(db_column='Email Address', max_length=50, unique=True)),
                ('phone_number', models.CharField(db_column='Phone Number', max_length=17)),
                ('room_number', models.CharField(db_column='Room Number', max_length=5)),
                ('subject_taught', models.TextField(db_column='Subjects taught', max_length=1)),
            ],
        ),
    ]
