# Generated by Django 3.1.6 on 2021-02-16 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='subject_taught',
            field=models.TextField(db_column='Subjects taught', max_length=100),
        ),
    ]
